---
- hosts: jenkins
  sudo: yes
  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.git
    - geerlingguy.ntp
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.java
    - geerlingguy.composer
    - geerlingguy.mysql

  tasks:

    - name: create the magento composer auth file
      template:
        src: templates/root/.composer/auth.json.j2
        dest: "{{ composer_home_path }}/auth.json"
        owner: "{{ composer_home_owner }}"
        group: "{{ composer_home_group }}"

    - name: create empty mysql database
      mysql_db:
        name: "{{ magento_db_name }}"
        state: present

    - name: create mysql user
      mysql_user:
        name: "{{ magento_db_user }}"
        password: "{{ magento_db_pass }}"
        priv: "{{ magento_db_name }}.*:ALL"
        state: present

    - name: get the swarm JAR
      get_url:
        url: "{{ jenkins_url }}swarm/swarm-client.jar"
        dest: /tmp/swarm-client.jar
        mode: 0555

    - name: associate machine with jenkins
    # Need to disown this
      command: "nohup java -jar /tmp/swarm-client.jar -master '{{ jenkins_url }}' -username '{{ jenkins_username }}' -password {{ jenkins_password }} -name {{ ansible_hostname }} -labels testMachine -executors 1  &"